kind: Secret
apiVersion: v1

metadata:
  name: {{ .Release.Name }}-secret

type: Opaque
stringData:
  NEXTAUTH_SECRET: "{{ .Values.Secret.NEXTAUTH_SECRET }}"
  JWT_SECRET: "{{ .Values.Secret.JWT_SECRET }}"
